### ISSUE TITLE
wiki/install Golang

### ISSUE THREAD

**Issue by cfauci** [vertgenlab/gonomics#848]
This document has not information about how it's supposed to be used and since we already direct them to the golang website elsewhere I think we should drop it or we need to give it a lot more context and documentation

**Comment by edotau** [comment]
We can delete it. I think I added this a while back as a bash script to download golang and set up the appropriate paths but I think software installations have come a long way since then and this solution is much more built out

**Comment by cfauci** [comment]
that's what it seemed like, great, I'll delete it!
